---
 - hosts: local
   become: yes
   become_user: root
   tasks:
    - name: instalaci贸n ssh lisa
      lxc_container:
        name: lisa
        container_command: yum update | yum install openssh-server sshpass sudo.x86_64  -y

    - name: creaci贸n de usuario
      lxc_container:
        name: lisa
        container_command: useradd usuario -s /bin/bash -m 

    - name: configuraci贸n del usuario
      lxc_container:
        name: lisa
        container_command: |
          echo -e "usuario\nusuario" | passwd usuario

    - name: configuraci贸n de sudo
      lxc_container:
        name: lisa
        container_command: |
          echo "usuario ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
