---
 - hosts: local
   become: yes
   become_user: root
   tasks:
    - name: instalaci贸n ssh server, sshpass y python-minimal en homer
      lxc_container:
        name: homer
        container_command: |
          apt-get update | apt-get install openssh-server sshpass python-minimal  -y

    - name: creaci贸n de usuario
      lxc_container:
        name: homer
        container_command: useradd usuario -s /bin/bash -m 

    - name: configuraci贸n del usuario
      lxc_container:
        name: homer
        container_command: |
          echo -e "usuario\nusuario" | passwd usuario

    - name: configuraci贸n de sudo
      lxc_container:
        name: homer
        container_command: |
          echo "usuario ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
