---
 - name: instalación de dns
   apt: name=bind9 state=present
 
 - name: configurando zona directa
   template: 
     src: roles/dns/files/db.arodriguez
     dest: /var/cache/bind/db.arodriguez
     owner: root
     group: root
     mode: 0644

 - name: configurando conf.local
   template:
     src: roles/dns/files/db.named.conf.local
     dest: /etc/bind/named.conf.local
     owner: root
     group: root
     mode: 0644


 - name: configurando zona inversa
   template:
     src: roles/dns/files/db.10.0.4
     dest: /var/cache/bind/db.10.0.4
     owner: root
     group: root
     mode: 0644

 - name: reinicio de bind
   service:
     name: bind9
     state: restarted
